---
syncthing_directory: "{{ ansible_env.HOME }}/Syncthing"
syncthing_config_directory: "{{ syncthing_directory }}/Config"
syncthing_data_directory: "{{ syncthing_directory }}/Data"
podman_quadlets_directory: "{{ xdg_config_dir }}/containers/systemd"
podman_quadlets_user_uid: "1000"
podman_quadlets_keep_id_setting: "keep-id:uid={{ podman_quadlets_user_uid }},gid={{ podman_quadlets_user_uid }}"
podman_quadlets:
  - description: "Syncthing Service"
    container_name: syncthing
    image: lscr.io/linuxserver/syncthing:latest
    # entrypoint: /bin/syncthing
    network: host
    publish_ports:
      # - "127.0.0.1:8384:8384"
      - "8384:8384"
      - "22000:22000/tcp"
      - "22000:22000/udp"
      - "21027:21027/udp"
    user_ns: "{{ podman_quadlets_keep_id_setting }}"
    volume:
      - "{{ syncthing_config_directory }}:/config:Z,U"
      - "{{ syncthing_data_directory }}:/data:Z,U"
flatpak_apps:
  # brave: "com.brave.Browser"
  opera: "com.opera.Opera"
  thunderbird: "org.mozilla.Thunderbird"
  bitwarden: "com.bitwarden.desktop"
  kontainer: "io.github.DenysMb.Kontainer"
  boxbuddy: "io.github.dvlv.boxbuddyrs"
  libreoffice: "org.libreoffice.LibreOffice"
  onlyoffice: "org.onlyoffice.desktopeditors"
  obsidian: "md.obsidian.Obsidian"
  cantor: "org.kde.cantor"
  kalgebra: "org.kde.kalgebra"
  qalculate: "io.github.Qalculate"
  ptyxis: "app.devsuite.Ptyxis"
  yakuake: "org.kde.yakuake"
  plasmatube: "org.kde.plasmatube"
