---
- name: opencode | Setup opencode Config Directory | file
  file:
    path: "{{ opencode_config_dir }}"
    state: directory
    mode: '0755'

- name: opencode | Copy opencode Config Files | template
  ansible.builtin.template:
    src: "{{ item.src }}"
    dest: "{{ opencode_config_dir }}/{{ item.path | regex_replace('\\.j2$', '') }}"
  with_community.general.filetree: "../templates/opencode"
  when: item.state == 'file'
