---
- name: Vars | Set Mise Variables | set_fact
  ansible.builtin.set_fact:
    zsh_mise_env: |
      eval "$(mise activate zsh)"
    bash_mise_env: |
      eval "$(mise activate bash)"
    nu_mise_config: |
      use ($nu.default-config-dir | path join "mise.nu")
    nu_mise_env: |
      let mise_path = ($nu.default-config-dir | path join "mise.nu")
      ^mise activate nu | save --force $mise_path
    bash_fzf_path: ""
    zsh_fzf_path: ""
    tcsh_fzf_path: ""
    nushell_fzf_path: ""
    direnv_exe: "direnv"
    just_exe: "just"
    joplin_exe: "joplin"
    treesitter_compiler_exe: "gcc"
