---
neotest_adapters:
  - "{{ neotest_adapters_rust }}"
neotest_adapters_luafile: |
  {%- for neotest_adapter in neotest_adapters -%}
  {{ neotest_adapter }}
  {%- endfor -%}
nvim_test:
  lazy: |
    {
      'nvim-neotest/neotest',
      dependencies = {
        'nvim-neotest/nvim-nio',
        'nvim-lua/plenary.nvim',
        'antoinemadec/FixCursorHold.nvim',
      },
    },
  config: |
    require("neotest").setup({
      adapters = {% raw %}{{% endraw %}
        -- Language Adapters
        {{ neotest_adapters_luafile | indent(2) }}
        -- Language Adapters(End)
      {% raw %}}{% endraw %},
    })
  keymaps: |
    {
      icon = 'ï¼',
      mode = 'n',
      { '<leader>t', group = 'NeoTest', },
      { '<leader>tt', '<cmd>lua require("neotest").run.run()<CR>', desc = 'NeoTest: Run Nearest Test', },
      { '<leader>td', '<cmd>lua require("neotest").run.run({strategy = "dap"})<CR>', desc = 'NeoTest: Debug Nearest Test', },
    },
