---
yazi_config: "{{ xdg_config_dir }}/yazi"
yazi_config_file: "{{ yazi_config }}/yazi.toml"
yazi_plugin_dir: "{{ yazi_config }}/plugins"
yazi_flavors_dir: "{{ yazi_config }}/flavors"
yazi_dirs:
  - "{{ yazi_config }}"
  - "{{ yazi_plugin_dir }}"
  - "{{ yazi_flavors_dir }}"
yazi_exe: "yazi"
ya_exe: "ya"
yazi_package_cmd: "{{ ya_exe }} pack"
yazi_plugins:
  starship:
    name: starship
    url: "https://github.com/Rolv-Apneseth/starship.yazi"
    dest_name: "starship.yazi"
    pack: "Rolv-Apneseth/starship"
    config: |
      require("starship"):setup()
  # easyjump:
  #   name: easyjump
  #   url: "https://github.com/mikavilpas/easyjump.yazi"
  #   dest_name: "easyjump.yazi"
  #   pack: "mikavilpas/easyjump.yazi:easyjump"
  #   config: |
  #     require("easyjump"):setup()
  #   keymap: |
  #     [[manager.prepend_keymap]]
  #     on   = [ "i" ]
  #     run  = "plugin easyjump"
  #     desc = "easyjump"
# Pulled from: https://github.com/yazi-rs/flavors
yazi_themes:
  ayu-dark:
    pack: "ayu-dark"
    url: "https://github.com/kmlupreti/ayu-dark.yazi"
    dest_name: "ayu-dark.yazi"
  flexoki-light:
    pack: "flexoki-light"
    url: "https://github.com/gosxrgxx/flexoki-light.yazi"
    dest_name: "flexoki-light.yazi"
  flexoki-dark:
    pack: "flexoki-dark"
    url: "https://github.com/gosxrgxx/flexoki-dark.yazi"
    dest_name: "flexoki-dark.yazi"
  gruvbox-dark:
    pack: "gruvbox-dark"
    url: "https://github.com/bennyyip/gruvbox-dark.yazi"
    dest_name: "gruvbox-dark.yazi"
